stages:
  - install
  - lint
  - test

variables:
  NODE_ENV: development

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - services/*/node_modules/

install-dependencies:
  stage: install
  image: node:22
  script:
    - npm install
    - npm run install
  artifacts:
    paths:
      - node_modules/
      - services/*/node_modules/
    expire_in: 1h

lint-code:
  stage: lint
  image: node:22
  script:
    - npm run lint
  dependencies:
    - install-dependencies
  allow_failure: false

run-tests:
  stage: test
  image: node:22
  script:
    - npm run test
  dependencies:
    - install-dependencies
