sudo: required
language: node_js
node_js: 
  - "14.15"
services:
  - docker
env:
  NODE_CONFIG: '{ "smtp": { "secure": false, "ignoreTLS": true } }'
before_install:
  - sudo service docker restart
  - sleep 10
  - npm install
before_script:
  - docker-compose -f docker-compose.debug.yml up -d
  - until [[ "$(curl -u elastic:changeme -s -o null http://localhost:9200 -w %{http_code})" == *"200"* ]]; do echo 'Waiting for ElasticSearch sync'; sleep 10; done
script: "npm run test"
notifications:
  email:
    recipients:
      - ezteam@couperin.org
    on_success: change
    on_failure: always