sudo: required
language: node_js
node_js: 
  - "14.15"
services:
  - docker
env:
  NODE_ENV: 'development'
  NODE_CONFIG: |
    { "smtp": { "secure": false, "ignoreTLS": true } }
before_script:
  - docker-compose -f docker-compose.debug.yml up -d graphql update enrich elastic fakeunpaywall maildev
  - until [[ "$(curl -u elastic:changeme -s -o /dev/null http://localhost:9200 -w %{http_code})" -eq 200 ]]; do echo 'Waiting for ElasticSearch sync'; sleep 5; done
script: "npm run test"
notifications:
  email:
    recipients:
      - ezteam@couperin.org
    on_success: change
    on_failure: always