sudo: required
language: node_js
node_js: 
  - "14.15"
services:
  - docker
env:
  NODE_ENV: 'development'
  NODE_CONFIG: |
    { "smtp": { "secure": false, "ignoreTLS": true } }
before_script:
  - docker-compose -f docker-compose.debug.yml run --rm elastic chown -R elasticsearch /usr/share/elasticsearch/
  - docker-compose -f docker-compose.debug.yml up -d elastic fakeunpaywall maildev
  - docker-compose -f docker-compose.debug.yml up -d auth redis
    - docker-compose -f docker-compose.debug.yml up -d graphql update enrich 
script: "npm run test"
notifications:
  email:
    recipients:
      - ezteam@couperin.org
    on_success: change
    on_failure: always