version: "3.3"

services:
  graphql:
    build:
      context: ./src/graphql
      args:
        - http_proxy
        - https_proxy
    container_name: prod-graphql
    environment:
      - NODE_ENV=production
      # elastic
      - ELASTICSEARCH_HOSTS
      - EZMETA_ELASTICSEARCH_PORT
      - EZMETA_ELASTICSEARCH_USERNAME
      - EZMETA_ELASTICSEARCH_PASSWORD
      - EZMETA_ELASTICSEARCH_INDEX_ALIAS
      # proxy
      - http_proxy
      - https_proxy
      # redis
      - EZUNPAYWALL_REDIS_HOST
      - EZUNPAYWALL_REDIS_PORT
      - EZUNPAYWALL_REDIS_PASSWORD
      # log
      - EZUNPAYWALL_GRAPHQL_LOG_PATH
      - EZUNPAYWALL_GRAPHQL_ACCESS_LOG_PATH
    volumes:
      - ${EZUNPAYWALL_GRAPHQL_APPLICATION_LOG_PATH:-./src/graphql/log/application}:/graphql/log/application
      - ${EZUNPAYWALL_GRAPHQL_ACCESS_LOG_PATH:-./src/graphql/log/access}:/graphql/log/access
    command: "npm start"
    ports:
      - ${EZUNPAYWALL_GRAPHQL_PORT:-3000}:3000
    depends_on:
      - redis
    restart: unless-stopped

  update:
    build:
      context: ./src/update
      args:
        - http_proxy
        - https_proxy
    container_name: prod-preprod
    environment:
      - NODE_ENV=production
       # unpaywall
      - EZUNPAYWALL_UPDATE_UNPAYWALL_APIKEY
      - EZUNPAYWALL_UPDATE_UNPAYWALL_URL=http://api.unpaywall.org
      # elastic
      - EZMETA_ELASTICSEARCH_HOST
      - EZMETA_ELASTICSEARCH_PORT
      - EZMETA_ELASTICSEARCH_USERNAME
      - EZMETA_ELASTICSEARCH_PASSWORD
      - EZMETA_ELASTICSEARCH_INDEX_ALIAS
      # redis
      - EZUNPAYWALL_REDIS_HOST
      - EZUNPAYWALL_REDIS_PORT
      - EZUNPAYWALL_REDIS_PASSWORD
      # proxy
      - http_proxy
      - https_proxy
      # log
      - EZUNPAYWALL_UPDATE_APPLICATION_LOG_PATH
      - EZUNPAYWALL_UPDATE_ACCESS_LOG_PATH
      # data
      - EZUNPAYWALL_UPDATE_DATA_PATH
    volumes:
      - ${EZUNPAYWALL_UPDATE_APPLICATION_LOG_PATH:-./src/update/log/application}:/update/log/application
      - ${EZUNPAYWALL_UPDATE_ACCESS_LOG_PATH:-./src/update/log/access}:/update/log/access
      - ${EZUNPAYWALL_UPDATE_DATA_PATH:-./src/update/data}:/update/data
    command: "npm start"
    ports:
      - ${EZUNPAYWALL_UPDATE_PORT:-4000}:3000
    depends_on:
      - redis
    restart: unless-stopped

  enrich:
    build:
      context: ./src/enrich
      args:
        - http_proxy
        - https_proxy
    container_name: prod-enrich
    environment:
      - NODE_ENV=production
      # redis
      - EZUNPAYWALL_REDIS_HOST
      - EZUNPAYWALL_REDIS_PORT
      - EZUNPAYWALL_REDIS_PASSWORD
      # graphql
      - EZUNPAYWALL_GRAPHQL_URL
      # log
      - EZUNPAYWALL_ENRICH_LOG_PATH
      - EZUNPAYWALL_ENRICH_ACCESS_LOG_PATH
      # data
      - EZUNPAYWALL_ENRICH_DATA_PATH
    volumes:
      - ${EZUNPAYWALL_ENRICH_APPLICATION_LOG_PATH:-./src/enrich/log/application}:/enrich/log/application
      - ${EZUNPAYWALL_ENRICH_ACCESS_LOG_PATH:-./src/enrich/log/access}:/enrich/log/access
      - ${EZUNPAYWALL_ENRICH_DATA_PATH:-./src/enrich/data}:/enrich/data
    command: "npm start"
    ports:
      - ${EZUNPAYWALL_ENRICH_PORT:-5000}:3000
    depends_on:
      - redis
    restart: unless-stopped

  apikey:
    build:
      context: ./src/apikey
      args:
        - http_proxy
        - https_proxy
    container_name: prod-apikey
    environment:
      # redis
      - EZUNPAYWALL_REDIS_HOST
      - EZUNPAYWALL_REDIS_PORT
      - EZUNPAYWALL_REDIS_PASSWORD
      # log
      - EZUNPAYWALL_APIKEY_LOG_PATH
      - EZUNPAYWALL_APIKEY_ACCESS_LOG_PATH
    volumes:
      - ${EZUNPAYWALL_APIKEY_APPLICATION_LOG_PATH:-./src/apikey/log/application}:/apikey/log/application
      - ${EZUNPAYWALL_APIKEY_ACCESS_LOG_PATH:-./src/apikey/log/access}:/apikey/log/access
    command: "npm start"
    ports:
      - 7000:3000
    depends_on:
      - redis
    restart: unless-stopped
    
  mail:
    build:
      context: ./src/mail
      args:
        - http_proxy
        - https_proxy
    container_name: mail-preprod
    environment:
      # mail
      - NODE_CONFIG
      - EZUNPAYWALL_MAIL_SMTP_HOST
      - EZUNPAYWALL_MAIL_SMTP_PORT
      - EZUNPAYWALL_MAIL_NOTIFICATIONS_SENDER
      - EZUNPAYWALL_MAIL_NOTIFICATIONS_RECEIVERS
      - EZUNPAYWALL_MAIL_NOTIFICATIONS_MACHINE
      # log
      - EZUNPAYWALL_MAIL_APPLICATION_LOG_PATH
      - EZUNPAYWALL_MAIL_ACCESS_LOG_PATH
    volumes:
      - ${EZUNPAYWALL_MAIL_APPLICATION_LOG_PATH:-./src/mail/log/application}:/mail/log/application
      - ${EZUNPAYWALL_MAIL_ACCESS_LOG_PATH:-./src/mail/log/access}:/mail/log/access
    command: "npm start"
    ports:
      - ${EZUNPAYWALL_MAIL_PORT:-8000}:3000
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      args:
        - http_proxy
        - https_proxy
    container_name: prod-frontend
    command: "npm run start"
    ports:
     - ${EZUNPAYWALL_FRONTEND_PORT:-8080}:3000
    environment:
      # graphql
      - EZUNPAYWALL_GRAPHQL_URL
      # update
      - EZUNPAYWALL_UPDATE_URL
      # enrich
      - EZUNPAYWALL_ENRICH_URL
      # mail
      - EZUNPAYWALL_MAIL_URL
      - EZUNPAYWALL_MAIL_APIKEY

  redis:
    image: redis:6.2.5-alpine3.14
    container_name: prod-redis
    command: redis-server --requirepass "${EZUNPAYWALL_REDIS_PASSWORD}"
    volumes:
      - ${EZUNPAYWALL_REDIS_DATA_PATH:-./data/redis}:/data
    ports:
      - ${EZUNPAYWALL_REDIS_PORT:-6379}:6379
    restart: unless-stopped

  nginx:
    image: nginx:1.20.1-alpine
    container_name: prod-nginx
    ports:
      - ${EZUNPAYWALL_NGINX_PORT:-80}:80
    environment:
      - EZUNPAYWALL_NGINX_HOST
    volumes:
      - "./src/nginx/templates/http.conf.template:/etc/nginx/templates/default.conf.template:ro"
    restart: unless-stopped
    depends_on:
      - enrich
      - update
      - graphql
      - apikey
      - frontend
