version: "3.3"

services:
  graphql:
    build:
      context: ./services/graphql
    container_name: ezunpaywall-graphql-prod
    environment:
      - NODE_ENV=production
      - PORT
      # elastic
      - ELASTICSEARCH_HOSTS
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_INDEX_ALIAS
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    volumes:
      - ${GRAPHQL_APPLICATION_LOG_PATH:-./services/graphql/log/application}:/usr/src/app/log/application
      - ${GRAPHQL_ACCESS_LOG_PATH:-./services/graphql/log/access}:/usr/src/app/log/access
      - ${ELASTIC_CERT_CA_PATH:-./services/graphql/certs/ca.crt}:/usr/src/app/certs
    command: "npm start"
    restart: unless-stopped

  enrich:
    build:
      context: ./services/enrich
    container_name: ezunpaywall-enrich-prod
    environment:
      - NODE_ENV=production
      - PORT
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      # graphql
      - GRAPHQL_URL
      - GRAPHQL_PORT
    volumes:
      - ${ENRICH_APPLICATION_LOG_PATH:-./services/enrich/log/application}:/usr/src/app/log/application
      - ${ENRICH_ACCESS_LOG_PATH:-./services/enrich/log/access}:/usr/src/app/log/access
      - ${ENRICH_DATA_PATH:-./services/enrich/data}:/usr/src/app/data
    command: "npm start"
    restart: unless-stopped

  admin:
    build:
      context: ./services/admin
    container_name: ezunpaywall-admin-prod
    environment:
      - NODE_ENV
      - PORT
      - LOG_LEVEL=debug
      # smtp
      - SMTP_HOST=maildev
      - SMTP_PORT
      # mail
      - NOTIFICATIONS_SENDER
      - NOTIFICATIONS_RECEIVERS
      - NOTIFICATIONS_MACHINE
      # unpaywall
      - UNPAYWALL_APIKEY
      - UNPAYWALL_URL
      # elastic
      - ELASTICSEARCH_NODES
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_INDEX_ALIAS
      - ELASTICSEARCH_TIMEOUT
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      # cron snapshot
      - CRON_DOWNLOAD_SNAPSHOT_SCHEDULE
      - CRON_DOWNLOAD_SNAPSHOT_ACTIVE
      - CRON_DOWNLOAD_SNAPSHOT_INDEX
      # cron date update
      - CRON_DATA_UPDATE_SCHEDULE
      - CRON_DATA_UPDATE_ACTIVE
      - CRON_DATA_UPDATE_INDEX
      - CRON_DATA_UPDATE_INTERVAL
      # cron date update history
      - CRON_DATA_UPDATE_HISTORY_SCHEDULE
      - CRON_DATA_UPDATE_HISTORY_ACTIVE
      - CRON_DATA_UPDATE_HISTORY_INDEX
      - CRON_DATA_UPDATE_HISTORY_INDEX_HISTORY
      - CRON_DATA_UPDATE_HISTORY_INTERVAL
      # cron clean file
      - CRON_CLEAN_FILE_SCHEDULE
      - CRON_CLEAN_FILE_CHANGEFILE_THRESHOLD
      - CRON_CLEAN_FILE_REPORT_THRESHOLD
      - CRON_CLEAN_FILE_SNAPSHOT_THRESHOLD
      # password
      - ADMIN_APIKEY
      # health
      - HEALTH_TIMEOUT
    volumes:
      - ${ADMIN_APPLICATION_LOG_PATH:-./services/admin/log/application}:/usr/src/app/log/application
      - ${ADMIN_ACCESS_LOG_PATH:-./services/admin/log/access}:/usr/src/app/log/access
      - ${ADMIN_DATA_PATH:-./services/admin/data}:/usr/src/app/data
      - ${ELASTIC_CERT_CA_PATH-./services/admin/certs/ca.crt}:/usr/src/app/certs
    command: "npm run start"
    restart: unless-stopped

  frontend:
    build:
      context: ./services/frontend
    container_name: ezunpaywall-frontend-prod
    environment:
      - NODE_ENV=production
      - NUXT_PORT
      - NUXT_PUBLIC_ENVIRONMENT=development
      - NUXT_PUBLIC_ELASTIC_ENV=development
      - NUXT_PUBLIC_VERSION=development
      - NUXT_PUBLIC_UNPAYWALL_HOMEPAGE_URL
      - NUXT_PUBLIC_UNPAYWALL_API_URL
      - NUXT_PUBLIC_UNPAYWALL_URL
      - NUXT_PUBLIC_GRAPHQL_URL=http://localhost/api
      - NUXT_PUBLIC_ENRICH_URL=http://localhost/api/enrich
      - NUXT_PUBLIC_ADMIN_URL=http://localhost/api/admin
      - NUXT_ADMIN_APIKEY

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: ezunpaywall-redis-prod
    command: redis-server --requirepass "${REDIS_PASSWORD:-changeme}"
    volumes:
      - ${REDIS_DATA_PATH:-./data/redis}:/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli --pass changeme ping | grep PONG"
        ]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    build:
      context: ./services/nginx
    container_name: ezunpaywall-nginx-prod
    environment:
      # host of service
      - NGINX_HOST
      - FRONTEND_URL=http://frontend:3000/
      - GRAPHQL_URL=http://graphql:3001/
      - ENRICH_URL=http://enrich:3002/
      - ADMIN_URL=http://admin:3003/
    ports:
      - ${NGINX_PORT:-80}:80
    restart: unless-stopped
    depends_on:
      graphql:
        condition: service_healthy
      enrich:
        condition: service_healthy
      admin:
        condition: service_healthy
      frontend:
        condition: service_healthy

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: ezunpaywall-elastic-prod
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME={ELASTICSEARCH_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./data/elastic:/usr/share/elasticsearch/data"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --fail http://elastic:changeme@localhost:9200"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: ezunpaywall-kibana-prod
    environment:
      - ELASTICSEARCH_HOSTS="http://elastic:9200"
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - xpack.security.enabled=true
    depends_on: 
      elastic:
        condition: service_healthy
    ports:
      - 5601:5601
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --fail http://elastic:changeme@localhost:5601/api/status"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
