version: "3.3"

services:
  graphql:
    build:
      context: ./services/graphql
    container_name: ezunpaywall-graphql

  enrich:
    build:
      context: ./services/enrich
    container_name: ezunpaywall-enrich

  admin:
    build:
      context: ./services/admin
    container_name: ezunpaywall-admin

  frontend:
    build:
      context: ./services/frontend
    container_name: ezunpaywall-frontend

  nginx:
    build:
      context: ./services/nginx
    container_name: ezunpaywall-nginx
