version: "3.3"

services:
  graphql:
    build:
      context: ./src/graphql
      args:
        - http_proxy
        - https_proxy
    container_name: graphql-preprod
    environment:
      - NODE_ENV=production
      # elastic
      - ELASTICSEARCH_HOSTS
      - EZMETA_ELASTICSEARCH_PORT
      - EZMETA_ELASTICSEARCH_USERNAME
      - EZMETA_ELASTICSEARCH_PASSWORD
      - EZMETA_ELASTICSEARCH_INDEX_ALIAS
      # proxy
      - http_proxy
      - https_proxy
      # redis
      - EZUNPAYWALL_REDIS_HOST
      - EZUNPAYWALL_REDIS_PORT
      - EZUNPAYWALL_REDIS_PASSWORD
      # log
      - EZUNPAYWALL_GRAPHQL_LOG_PATH
      - EZUNPAYWALL_GRAPHQL_ACCESS_LOG_PATH
    volumes:
      - $HOME/var/log/ezunpaywall/graphql:/graphql/log
    command: "npm start"
    ports:
      - 3000:3000
    depends_on:
      - redis
    restart: unless-stopped

  update:
    build:
      context: ./src/update
      args:
        - http_proxy
        - https_proxy
    container_name: update-preprod
    environment:
      - NODE_ENV=production
       # unpaywall
      - EZUNPAYWALL_UPDATE_UNPAYWALL_APIKEY
      - EZUNPAYWALL_UPDATE_UNPAYWALL_URL=http://api.unpaywall.org
      # elastic
      - EZMETA_ELASTICSEARCH_HOST
      - EZMETA_ELASTICSEARCH_PORT
      - EZMETA_ELASTICSEARCH_USERNAME
      - EZMETA_ELASTICSEARCH_PASSWORD
      - EZMETA_ELASTICSEARCH_INDEX_ALIAS
      # redis
      - EZUNPAYWALL_REDIS_HOST
      - EZUNPAYWALL_REDIS_PORT
      - EZUNPAYWALL_REDIS_PASSWORD
      # proxy
      - http_proxy
      - https_proxy
      # log
      - EZUNPAYWALL_UPDATE_LOG_PATH
      - EZUNPAYWALL_UPDATE_ACCESS_LOG_PATH
    volumes:
      - ~/var/log/ezunpaywall/update:/update/log
      - ./src/update/data:/update/data
    command: "npm start"
    ports:
      - 4000:3000
    depends_on:
      - redis
    restart: unless-stopped

  enrich:
    build:
      context: ./src/enrich
      args:
        - http_proxy
        - https_proxy
    container_name: enrich-preprod
    environment:
      - NODE_ENV=production
      # elastic
      - EZMETA_ELASTICSEARCH_HOST
      - EZMETA_ELASTICSEARCH_PORT
      - EZMETA_ELASTICSEARCH_USERNAME
      - EZMETA_ELASTICSEARCH_PASSWORD
      # redis
      - EZUNPAYWALL_REDIS_HOST
      - EZUNPAYWALL_REDIS_PORT
      - EZUNPAYWALL_REDIS_PASSWORD
      # graphql
      - EZUNPAYWALL_GRAPHQL_URL
      # log
      - EZUNPAYWALL_ENRICH_LOG_PATH
      - EZUNPAYWALL_ENRICH_ACCESS_LOG_PATH
    volumes:
      - ~/var/log/ezunpaywall/enrich:/enrich/log
      - ./src/enrich/data:/enrich/data
    command: "npm start"
    ports:
      - 5000:3000
    depends_on:
      - redis
    restart: unless-stopped

  apikey:
    build:
      context: ./src/apikey
      args:
        - http_proxy
        - https_proxy
    container_name: apikey-preprod
    environment:
      # redis
      - EZUNPAYWALL_REDIS_HOST
      - EZUNPAYWALL_REDIS_PORT
      - EZUNPAYWALL_REDIS_PASSWORD
      # log
      - EZUNPAYWALL_APIKEY_LOG_PATH
    volumes:
      - ./src/apikey:/apikey
    command: "npm start"
    ports:
      - 7000:3000
    depends_on:
      - redis
    restart: unless-stopped
    
  mail:
    build:
      context: ./src/mail
      args:
        - http_proxy
        - https_proxy
    container_name: mail-preprod
    environment:
      # mail
      - NODE_CONFIG
      - EZUNPAYWALL_MAIL_SMTP_HOST
      - EZUNPAYWALL_MAIL_SMTP_PORT
      - EZUNPAYWALL_MAIL_NOTIFICATIONS_SENDER
      - EZUNPAYWALL_MAIL_NOTIFICATIONS_RECEIVERS
      - EZUNPAYWALL_MAIL_NOTIFICATIONS_MACHINE
      # log
      - MAIL_LOG_PATH
    volumes:
      - ./src/mail:/mail
    command: "npm start"
    ports:
      - 8000:3000
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      args:
        - http_proxy
        - https_proxy
    container_name: frontend-preprod
    command: "npm run start"
    ports:
      - 8080:8080
    environment:
      # graphql
      - EZUNPAYWALL_GRAPHQL_URL
      # update
      - EZUNPAYWALL_UPDATE_URL
      # enrich
      - EZUNPAYWALL_ENRICH_URL
      # mail
      - EZUNPAYWALL_MAIL_URL
      - EZUNPAYWALL_MAIL_APIKEY

  redis:
    image: redis:6.2.5-alpine3.14
    container_name: redis-preprod
    command: redis-server --requirepass "${EZUNPAYWALL_REDIS_PASSWORD:-changeme}"
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped

  nginx:
    image: nginx:1.20.1-alpine
    container_name: nginx
    ports: 
      - 80:80
    environment:
      - EZUNPAYWALL_NGINX_HOST
    volumes:
      - "./src/nginx/templates/http.conf.template:/etc/nginx/templates/default.conf.template:ro"
    restart: unless-stopped
    depends_on:
      - enrich
      - update
      - graphql
      - apikey
      - frontend

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elastic-preprod
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    healthcheck:
      test: curl --cacert $CERTS_DIR_ES/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./data/elastic:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    restart: unless-stopped     