version: "3.3"

services:
  graphql:
    build:
      context: ./src/graphql
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=production
      # elastic
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-http://elastic}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - ELASTICSEARCH_INDEX_ALIAS
      # proxy
      - http_proxy
      - https_proxy
      # redis password
      - REDIS_PASSWORD
    volumes:
      - $HOME/var/log/ezunpaywall/graphql:/usr/src/graphql/log
    command: "npm start"
    ports:
      - 3000:3000
    depends_on:
      - redis
    restart: unless-stopped

  update:
    build:
      context: ./src/update
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=production
      # mail
      - NODE_CONFIG
      - EZUNPAYWALL_SMTP_HOST
      - EZUNPAYWALL_SMTP_PORT
      - EZUNPAYWALL_NOTIFICATIONS_SENDER
      - EZUNPAYWALL_NOTIFICATIONS_RECEIVERS
      - EZUNPAYWALL_NOTIFICATIONS_MACHINE
       # unpaywall
      - API_KEY_UPW
      - UNPAYWALL_URL=http://api.unpaywall.org/feed/changefiles
      # elastic
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-http://elastic}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - ELASTICSEARCH_INDEX_ALIAS
      # proxy
      - http_proxy
      - https_proxy
      # redis
      - REDIS_PASSWORD
    volumes:
      - $HOME/var/log/ezunpaywall/update:/usr/src/update/log
      - ./src/update/out:/usr/src/update/out
    command: "npm start"
    ports:
      - 4000:4000
    depends_on:
      - redis
    restart: unless-stopped

  enrich:
    build:
      context: ./src/enrich
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=production
      # elastic
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-http://elastic}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      # redis
      - REDIS_PASSWORD
      # URL services
      - GRAPHQL_URL
    volumes:
      - $HOME/var/log/ezunpaywall/enrich:/usr/src/enrich/log
      - ./src/enrich/out:/usr/src/enrich/out
    command: "npm start"
    ports:
      - 5000:5000
    depends_on:
      - redis
    restart: unless-stopped

  apikey:
    build:
      context: ./src/apikey
      args:
        - http_proxy
        - https_proxy
    environment:
      - REDIS_PASSWORD
    command: "npm start"
    ports:
      - 7000:7000
    depends_on:
      - redis
    restart: unless-stopped

  mail:
    build:
      context: ./src/mail
      args:
        - http_proxy
        - https_proxy
    environment:
      # mail
      - NODE_CONFIG
      - EZUNPAYWALL_SMTP_HOST
      - EZUNPAYWALL_SMTP_PORT
      - EZUNPAYWALL_NOTIFICATIONS_SENDER
      - EZUNPAYWALL_NOTIFICATIONS_RECEIVERS
      - EZUNPAYWALL_NOTIFICATIONS_MACHINE
    volumes:
      - ./src/mail:/mail
    command: "npm start"
    ports:
      - 8000:8000
    restart: unless-stopped

  redis:
    image: "redis:6.2.5-alpine3.14"
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
    volumes:
      - ./data-redis:/home/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  rp:
    build:
      context: .
      dockerfile: ./rp/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - GRAPHQL_URL=${GRAPHQL_URL:-http://graphql}
        - UPDATE_URL=${UPDATE_URL:-http://update}
        - ENRICH_URL=${ENRICH_URL:-http://enrich}
    ports:
      - 59700:80
    environment:
      - NGINX_HOST
    volumes:
      - "./rp/templates/http.conf.template:/etc/nginx/templates/default.conf.template:ro"
    restart: unless-stopped
    depends_on:
      - enrich
      - update
      - graphql
      - apikey