version: "3.3"

services:
  graphql:
    build:
      context: ./src/graphql
      args:
        - http_proxy
        - https_proxy
    container_name: ezunpaywall-graphql-prod
    environment:
      - NODE_ENV=production
      # proxy
      - http_proxy
      - https_proxy
      # elastic
      - ELASTICSEARCH_HOSTS
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_INDEX_ALIAS
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    volumes:
      - ${GRAPHQL_APPLICATION_LOG_PATH:-./src/graphql/log/application}:/graphql/log/application
      - ${GRAPHQL_ACCESS_LOG_PATH:-./src/graphql/log/access}:/graphql/log/access
      - ${EZMETA_CERTS_PATH:-./src/graphql/certs/ca.crt}:/graphql/certs
    command: "npm start"
    ports:
      - ${GRAPHQL_PORT:-59701}:3000
    depends_on:
      - redis
    restart: unless-stopped

  update:
    build:
      context: ./src/update
      args:
        - http_proxy
        - https_proxy
    container_name: ezunpaywall-update-preprod
    environment:
      - NODE_ENV=production
      # proxy
      - http_proxy
      - https_proxy
      # unpaywall
      - UPDATE_UNPAYWALL_APIKEY
      - UPDATE_UNPAYWALL_HOST=http://api.unpaywall.org
      # elastic
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_INDEX_ALIAS
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    volumes:
      - ${UPDATE_APPLICATION_LOG_PATH:-./src/update/log/application}:/update/log/application
      - ${UPDATE_ACCESS_LOG_PATH:-./src/update/log/access}:/update/log/access
      - ${UPDATE_DATA_PATH:-./src/update/data}:/update/data
      - ${EZMETA_CERTS_PATH-./src/update/certs/ca.crt}:/update/certs
    command: "npm start"
    ports:
      - ${UPDATE_PORT:-59702}:3000
    depends_on:
      - redis
    restart: unless-stopped

  enrich:
    build:
      context: ./src/enrich
      args:
        - http_proxy
        - https_proxy
    container_name: ezunpaywall-enrich-prod
    environment:
      - NODE_ENV=production
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      # graphql
      - GRAPHQL_HOST
    volumes:
      - ${ENRICH_APPLICATION_LOG_PATH:-./src/enrich/log/application}:/enrich/log/application
      - ${ENRICH_ACCESS_LOG_PATH:-./src/enrich/log/access}:/enrich/log/access
      - ${ENRICH_DATA_PATH:-./src/enrich/data}:/enrich/data
    command: "npm start"
    ports:
      - ${ENRICH_PORT:-59703}:3000
    depends_on:
      - redis
    restart: unless-stopped

  apikey:
    build:
      context: ./src/apikey
      args:
        - http_proxy
        - https_proxy
    container_name: ezunpaywall-apikey-prod
    environment:
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    volumes:
      - ${APIKEY_APPLICATION_LOG_PATH:-./src/apikey/log/application}:/apikey/log/application
      - ${APIKEY_ACCESS_LOG_PATH:-./src/apikey/log/access}:/apikey/log/access
    command: "npm start"
    ports:
      - ${APIKEY_PORT:-59704}:3000
    depends_on:
      - redis
    restart: unless-stopped
    
  mail:
    build:
      context: ./src/mail
      args:
        - http_proxy
        - https_proxy
    container_name: ezunpaywall-mail-prod
    environment:
      # mail
      - NODE_CONFIG
      - MAIL_SMTP_HOST
      - MAIL_SMTP_PORT
      - MAIL_NOTIFICATIONS_SENDER
      - MAIL_NOTIFICATIONS_RECEIVERS
      - MAIL_NOTIFICATIONS_MACHINE
    volumes:
      - ${MAIL_APPLICATION_LOG_PATH:-./src/mail/log/application}:/mail/log/application
      - ${MAIL_ACCESS_LOG_PATH:-./src/mail/log/access}:/mail/log/access
    command: "npm start"
    ports:
      - ${MAIL_PORT:-59705}:3000
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      args:
        - http_proxy
        - https_proxy
    container_name: ezunpaywall-frontend-prod
    command: "npm run start"
    ports:
     - ${FRONTEND_PORT:-59706}:3000
    environment:
      # graphql
      - GRAPHQL_HOST
      # update
      - UPDATE_HOST
      # enrich
      - ENRICH_HOST
      # mail
      - MAIL_HOST
      - MAIL_APIKEY

  redis:
    image: redis:6.2.5-alpine3.14
    container_name: ezunpaywall-redis-prod
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ${REDIS_DATA_PATH:-./data/redis}:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: unless-stopped

  nginx:
    image: nginx:1.20.1-alpine
    container_name: ezunpaywall-nginx-prod
    ports:
      - ${NGINX_PORT:-80}:80
    environment:
      - NGINX_HOST
    volumes:
      - ${NGINX_CONFIG_PATH:-./src/nginx/templates/http.conf.template}:/etc/nginx/templates/default.conf.template:ro
      - ${NGINX_ACCESS_LOG_PATH:-./src/nginx/log}:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - enrich
      - update
      - graphql
      - apikey
      - frontend
