version: "3.3"

services:
  graphql:
    build:
      context: ./src/graphql
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=production
      # elastic
      - ELASTICSEARCH_HOSTS
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_INDEX_ALIAS
      # proxy
      - http_proxy
      - https_proxy
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      # log
      - GRAPHQL_LOG_PATH
      - GRAPHQL_ACCESS_LOG_PATH
    volumes:
      - $HOME/var/log/ezunpaywall/graphql:/usr/src/graphql/log
    command: "npm start"
    ports:
      - 3000:3000
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - elastic

  update:
    build:
      context: ./src/update
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=production
      # mail
      - NODE_CONFIG
      - EZUNPAYWALL_SMTP_HOST
      - EZUNPAYWALL_SMTP_PORT
      - EZUNPAYWALL_NOTIFICATIONS_SENDER
      - EZUNPAYWALL_NOTIFICATIONS_RECEIVERS
      - EZUNPAYWALL_NOTIFICATIONS_MACHINE
       # unpaywall
      - UNPAYWALL_APIKEY
      - UNPAYWALL_URL=http://api.unpaywall.org
      # elastic
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_INDEX_ALIAS
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      # proxy
      - http_proxy
      - https_proxy
      # log
      - UPDATE_LOG_PATH
      - UPDATE_ACCESS_LOG_PATH
    volumes:
      - ~/var/log/ezunpaywall/update:/usr/src/update/log
      - ./src/update/data:/usr/src/update/data
    command: "npm start"
    ports:
      - 4000:4000
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - elastic

  enrich:
    build:
      context: ./src/enrich
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=production
      # elastic
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      # graphql
      - GRAPHQL_URL
      # log
      - ENRICH_LOG_PATH
      - ENRICH_ACCESS_LOG_PATH
    volumes:
      - ~/var/log/ezunpaywall/enrich:/usr/src/enrich/log
      - ./src/enrich/data:/usr/src/enrich/data
    command: "npm start"
    ports:
      - 5000:5000
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - elastic

  apikey:
    build:
      context: ./src/apikey
      args:
        - http_proxy
        - https_proxy
    environment:
      - REDIS_PASSWORD
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      # log
      - APIKEY_LOG_PATH
    volumes:
      - ./src/apikey:/apikey
    command: "npm start"
    ports:
      - 7000:7000
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - elastic
    
  mail:
    build:
      context: ./src/mail
      args:
        - http_proxy
        - https_proxy
    environment:
      # mail
      - NODE_CONFIG
      - EZUNPAYWALL_SMTP_HOST
      - EZUNPAYWALL_SMTP_PORT
      - EZUNPAYWALL_NOTIFICATIONS_SENDER
      - EZUNPAYWALL_NOTIFICATIONS_RECEIVERS
      - EZUNPAYWALL_NOTIFICATIONS_MACHINE
      # log
      - MAIL_LOG_PATH
    volumes:
      - ./src/mail:/mail
    command: "npm start"
    ports:
      - 8000:8000
    restart: unless-stopped

  redis:
    image: redis:6.2.5-alpine3.14
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - elastic

  rp:
    build:
      context: .
      dockerfile: ./rp/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - GRAPHQL_URL
        - UPDATE_URL
        - ENRICH_URL
        - MAIL_URL 
    ports: 
      - 59700:80
    environment:
      - NGINX_HOST
    volumes:
      - "./src/rp/templates/http.conf.template:/etc/nginx/templates/default.conf.template:ro"
    restart: unless-stopped
    depends_on:
      - enrich
      - update
      - graphql
      - apikey
    networks:
      - elastic
  
networks:
  elastic:
    external: 
      name: ezmeta-single-node_elastic
