version: "3"

services:
  api:
    build:
      context: ./api
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=production
      # mail
      - NODE_CONFIG
      - EZUNPAYWALL_SMTP_HOST
      - EZUNPAYWALL_SMTP_PORT
      - EZUNPAYWALL_NOTIFICATIONS_SENDER
      - EZUNPAYWALL_NOTIFICATIONS_RECEIVERS
      # unpaywall
      - UNPAYWALL_URL
      - API_KEY_UPW
      # elastic
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      # proxy
      - http_proxy
      - https_proxy
    volumes:
      - ./api/out:/usr/src/api/out/
    command: "npm start"
    ports:
      - "8080:8080"
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        - http_proxy
        - https_proxy
    environment:
      - API_URL
      - HOST=0.0.0.0
      - PORT=3000
    command: "npm start"
    ports:
      - "3000:3000"
    restart: unless-stopped