version: "3"

services:
  api:
    build:
      context: ./api
      args:
        - http_proxy
        - https_proxy
    environment:
      # unpaywall
      - UNPAYWALL_URL=http://fakeunpaywall:12000/snapshots/changefiles.json
      - ELASTICSEARCH_HOST=http://elastic
      # proxy
      - http_proxy
      - https_proxy
    command: "npm start"
    ports:
      - "8080:8080"
    restart: unless-stopped      
      
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - CLUSTER_NAME=ezunpaywall
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    restart: unless-stopped

  fakeunpaywall:
    build:
      context: ./fakeUnpaywall
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
    command: "npm start"
    ports:
      - "12000:12000"
    restart: unless-stopped 
  