version: "3"

services:
  api:
    build:
      context: ./api
      args:
        - http_proxy
        - https_proxy
    environment:
      - NODE_ENV=production
      # mail
      - NODE_CONFIG
      - EZUNPAYWALL_SMTP_HOST
      - EZUNPAYWALL_SMTP_PORT
      - EZUNPAYWALL_NOTIFICATIONS_SENDER
      - EZUNPAYWALL_NOTIFICATIONS_RECEIVERS
      # unpaywall
      - UNPAYWALL_URL
      - API_KEY_UPW
      # elastic
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      # proxy
      - http_proxy
      - https_proxy
      # apikey
      - API_KEY_USERS
      - API_KEY_ADMIN
    volumes:
      - ./api/out:/usr/src/api/out/
    command: "npm start"
    ports:
      - "3000:3000"
    restart: unless-stopped

  rp:
    build:
      context: .
      dockerfile: ./rp/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - API_URL
    ports: 
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST
    volumes:
      - "./rp/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro"
      - "./rp/ssl/:/etc/nginx/ssl:ro"