const { paths, cron } = require('config');

const logger = require('../logger/appLogger');
const Cron = require('./cron');

const { deleteFilesInDir } = require('../lib/files');

const cronConfig = cron.cleanFile;

let { active } = cronConfig;
if (active === 'true' || active) active = true;
else active = false;

/**
 * Removes files generated by an update process that are older than 30 days.
 *
 * @returns {Promise<void>}
 */
async function task() {
  const deletedChangefiles = await deleteFilesInDir(
    paths.data.changefilesDir,
    cronConfig.changefileThreshold,
  );
  logger.info(`[cron][${this.name}]: ${deletedChangefiles?.join(',')} (${deletedChangefiles.length}) changefiles are deleted`);

  const deletedReportFiles = await deleteFilesInDir(
    paths.data.reportsDir,
    cronConfig.reportThreshold,
  );
  logger.info(`[cron][${this.name}]: ${deletedReportFiles?.join(',')} (${deletedReportFiles.length}) reports are deleted`);

  const deletedSnapshotFiles = await deleteFilesInDir(
    paths.data.snapshotsDir,
    cronConfig.snapshotsDir,
  );

  logger.info(`[cron][${this.name}]: ${deletedSnapshotFiles?.join(',')} (${deletedSnapshotFiles.length}) snapshots are deleted`);
}

const deleteFileCron = new Cron('Clean file', cronConfig.schedule, task, active);

module.exports = deleteFileCron;
