const availableAccess = ['enrich', 'graphql'];

const unpaywallAttrs = [
  '*',
  'doi',
  'data_standard',
  'title',
  'genre',
  'is_paratext',
  'published_date',
  'year',
  'doi_url',
  'journal_name',
  'journal_issns',
  'journal_issn_l',
  'journal_is_oa',
  'journal_is_in_doaj',
  'publisher',
  'is_oa',
  'oa_status',
  'has_repository_copy',
  'updated',

  'best_oa_location.url',
  'best_oa_location.url_for_landing_page',
  'best_oa_location.url_for_pdf',
  'best_oa_location.evidence',
  'best_oa_location.license',
  'best_oa_location.host_type',
  'best_oa_location.is_best',
  'best_oa_location.pmh_id',
  'best_oa_location.endpoint_id',
  'best_oa_location.repository_institution',
  'best_oa_location.oa_date',
  'best_oa_location.updated',

  'oa_locations.url',
  'oa_locations.url_for_landing_page',
  'oa_locations.url_for_pdf',
  'oa_locations.evidence',
  'oa_locations.license',
  'oa_locations.host_type',
  'oa_locations.is_best',
  'oa_locations.pmh_id',
  'oa_locations.endpoint_id',
  'oa_locations.repository_institution',
  'oa_locations.oa_date',
  'oa_locations.updated',

  'first_oa_location.url',
  'first_oa_location.url_for_landing_page',
  'first_oa_location.url_for_pdf',
  'first_oa_location.evidence',
  'first_oa_location.license',
  'first_oa_location.host_type',
  'first_oa_location.is_best',
  'first_oa_location.pmh_id',
  'first_oa_location.endpoint_id',
  'first_oa_location.repository_institution',
  'first_oa_location.oa_date',
  'first_oa_location.updated',

  'oa_locations_embargoed.url',
  'oa_locations_embargoed.url_for_landing_page',
  'oa_locations_embargoed.url_for_pdf',
  'oa_locations_embargoed.evidence',
  'oa_locations_embargoed.license',
  'oa_locations_embargoed.host_type',
  'oa_locations_embargoed.is_best',
  'oa_locations_embargoed.pmh_id',
  'oa_locations_embargoed.endpoint_id',
  'oa_locations_embargoed.repository_institution',
  'oa_locations_embargoed.oa_date',
  'oa_locations_embargoed.updated',

  'z_authors.author_position',
  'z_authors.given',
  'z_authors.raw_author_name',
  'z_authors.is_corresponding',
  'z_authors.raw_affiliation_strings',
];

module.exports = {
  availableAccess,
  unpaywallAttrs,
};
