const { paths, cron } = require('config');

const Cron = require('./cron');
const appLogger = require('../lib/logger/appLogger');

const { deleteFilesInDir } = require('../lib/file');

const cronConfig = cron.cleanFile;

let { active } = cronConfig;
if (active === 'true' || active) active = true;
else active = false;

/**
 * Removes files generated by an enrichment that are older than one day.
 *
 * @returns {Promise<void>}
 */
async function task() {
  appLogger.info('[cron][Clean file]: Has start');

  // Data
  const deletedEnrichedFiles = await
  deleteFilesInDir(paths.data.enrichedDir, cronConfig.enrichedFileRetention);
  appLogger.info(`[cron][Clean file]: ${deletedEnrichedFiles?.join(',')} (${deletedEnrichedFiles.length}) enriched files are deleted`);

  const deletedStatesFiles = await
  deleteFilesInDir(paths.data.statesDir, cronConfig.stateFileRetention);
  appLogger.info(`[cron][Clean file]: ${deletedStatesFiles?.join(',')} (${deletedStatesFiles.length}) states files are deleted`);

  const deletedUploadedFiles = await
  deleteFilesInDir(paths.data.uploadDir, cronConfig.uploadedFileRetention);
  appLogger.info(`[cron][Clean file]: ${deletedUploadedFiles?.join(',')} (${deletedUploadedFiles.length}) uploaded files are deleted`);

  // Logs
  const accessLogFiles = await deleteFilesInDir(
    paths.log.accessDir,
    cronConfig.accessLogRetention,
  );
  appLogger.info(`[cron][Clean file]: ${accessLogFiles?.join(',')} (${accessLogFiles.length}) access log file are deleted`);

  const applicationLogFile = await deleteFilesInDir(
    paths.log.applicationDir,
    cronConfig.applicationLogRetention,
  );
  appLogger.info(`[cron][Clean file]: ${applicationLogFile?.join(',')} (${applicationLogFile.length}) application log file are deleted`);

  const healthcheckLogFile = await deleteFilesInDir(
    paths.log.healthcheckDir,
    cronConfig.healthcheckLogRetention,
  );
  appLogger.info(`[cron][Clean file]: ${healthcheckLogFile?.join(',')} (${healthcheckLogFile.length}) healthcheck log file are deleted`);

  appLogger.info('[cron][Clean file]: Has finished');
}

const deleteFileCron = new Cron('Clean file', cronConfig.schedule, task, active);

/**
 * Update config of cron.
 *
 * @param {Object} newConfig Global config.
 */
function update(newConfig) {
  if (newConfig.schedule) {
    cronConfig.schedule = newConfig.schedule;
    deleteFileCron.setSchedule(newConfig.schedule);
  }
  if (newConfig.enrichedFileRetention) {
    cronConfig.enrichedFileRetention = newConfig.enrichedFileRetention;
  }
  if (newConfig.stateFileRetention) {
    cronConfig.stateFileRetention = newConfig.stateFileRetention;
  }

  if (newConfig.uploadedFileRetention) {
    cronConfig.uploadedFileRetention = newConfig.uploadedFileRetention;
  }
  if (newConfig.accessLogRetention) {
    cronConfig.accessLogRetention = newConfig.accessLogRetention;
  }
  if (newConfig.applicationLogRetention) {
    cronConfig.applicationLogRetention = newConfig.applicationLogRetention;
  }
  if (newConfig.healthcheckLogRetention) {
    cronConfig.healthcheckLogRetention = newConfig.healthcheckLogRetention;
  }

  if (newConfig.enrichedFileRetention
    || newConfig.stateFileRetention
    || newConfig.uploadedFileRetention
    || newConfig.accessLogRetention
    || newConfig.applicationLogRetention
    || newConfig.healthcheckLogRetention) {
    deleteFileCron.setTask(task);
  }
}

function getGlobalConfig() {
  const order = [
    'name',
    'schedule',
    'enrichedFileRetention',
    'stateFileRetention',
    'uploadedFileRetention',
    'accessLogRetention',
    'applicationLogRetention',
    'healthcheckLogRetention',
    'active',
  ];

  const data = { ...cronConfig, ...deleteFileCron.config };

  const result = {};
  order.forEach((key) => {
    if (data[key] !== undefined) {
      result[key] = data[key];
    }
  });
  return result;
}

module.exports = {
  getGlobalConfig,
  update,
  cron: deleteFileCron,
};
