const { paths, cron } = require('config');

const Cron = require('./cron');
const appLogger = require('../lib/logger/appLogger');

const { deleteFilesInDir } = require('../lib/file');

const cronConfig = cron.cleanFile;

let { active } = cronConfig;
if (active === 'true' || active) active = true;
else active = false;

/**
 * Removes files generated by an enrichment that are older than one day.
 *
 * @returns {Promise<void>}
 */
async function task() {
  appLogger.info('[cron][Clean file]: Has start');

  // Data
  const deletedEnrichedFiles = await
  deleteFilesInDir(paths.data.enrichedDir, cronConfig.enrichedFileThreshold);
  appLogger.info(`[cron][Clean file]: ${deletedEnrichedFiles?.join(',')} (${deletedEnrichedFiles.length}) enriched files are deleted`);

  const deletedStatesFiles = await
  deleteFilesInDir(paths.data.statesDir, cronConfig.stateFileThreshold);
  appLogger.info(`[cron][Clean file]: ${deletedStatesFiles?.join(',')} (${deletedStatesFiles.length}) states files are deleted`);

  const deletedUploadedFiles = await
  deleteFilesInDir(paths.data.uploadDir, cronConfig.uploadedFileThreshold);
  appLogger.info(`[cron][Clean file]: ${deletedUploadedFiles?.join(',')} (${deletedUploadedFiles.length}) uploaded files are deleted`);

  // Logs
  const accessLogFiles = await deleteFilesInDir(
    paths.log.accessDir,
    cronConfig.accessLogThreshold,
  );
  appLogger.info(`[cron][Clean file]: ${accessLogFiles?.join(',')} (${accessLogFiles.length}) access log file are deleted`);

  const applicationLogFile = await deleteFilesInDir(
    paths.log.applicationDir,
    cronConfig.applicationLogThreshold,
  );
  appLogger.info(`[cron][Clean file]: ${applicationLogFile?.join(',')} (${applicationLogFile.length}) application log file are deleted`);

  const healthcheckLogFile = await deleteFilesInDir(
    paths.log.healthcheckDir,
    cronConfig.healthcheckLogThreshold,
  );
  appLogger.info(`[cron][Clean file]: ${healthcheckLogFile?.join(',')} (${healthcheckLogFile.length}) healthcheck log file are deleted`);

  appLogger.info('[cron][Clean file]: Has finished');
}

const deleteFileCron = new Cron('Clean file', cronConfig.schedule, task, active);

/**
 * Update config of cron.
 *
 * @param {Object} newConfig Global config.
 */
function update(newConfig) {
  if (newConfig.schedule) {
    cronConfig.schedule = newConfig.schedule;
    deleteFileCron.setSchedule(newConfig.schedule);
  }
  if (newConfig.enrichedFileThreshold) {
    cronConfig.enrichedFileThreshold = newConfig.enrichedFileThreshold;
  }
  if (newConfig.stateFileThreshold) {
    cronConfig.stateFileThreshold = newConfig.stateFileThreshold;
  }

  if (newConfig.uploadedFileThreshold) {
    cronConfig.uploadedFileThreshold = newConfig.uploadedFileThreshold;
  }
  if (newConfig.accessLogThreshold) {
    cronConfig.accessLogThreshold = newConfig.accessLogThreshold;
  }
  if (newConfig.applicationLogThreshold) {
    cronConfig.applicationLogThreshold = newConfig.applicationLogThreshold;
  }
  if (newConfig.healthcheckLogThreshold) {
    cronConfig.healthcheckLogThreshold = newConfig.healthcheckLogThreshold;
  }

  if (newConfig.enrichedFileThreshold
    || newConfig.stateFileThreshold
    || newConfig.uploadedFileThreshold
    || newConfig.accessLogThreshold
    || newConfig.applicationLogThreshold
    || newConfig.healthcheckLogThreshold) {
    deleteFileCron.setTask(task);
  }
}

function getGlobalConfig() {
  const order = [
    'name',
    'schedule',
    'enrichedFileThreshold',
    'stateFileThreshold',
    'uploadedFileThreshold',
    'accessLogThreshold',
    'applicationLogThreshold',
    'healthcheckLogThreshold',
    'active',
  ];

  const data = { ...cronConfig, ...deleteFileCron.config };

  const result = {};
  order.forEach((key) => {
    if (data[key] !== undefined) {
      result[key] = data[key];
    }
  });
  return result;
}

module.exports = {
  getGlobalConfig,
  update,
  cron: deleteFileCron,
};
