const logger = require('../../logger');
const Cron = require('../../cron');
const dirPath = require('../../path');
const { deleteFilesInDir } = require('../../file');

const { reportsDir, snapshotsDir, statesDir } = dirPath;

/**
 * Removes files generated by an update process that are older than 30 days.
 *
 * @returns {Promise<void>}
 */
async function task() {
  const deletedReportFiles = await deleteFilesInDir(reportsDir, 30);
  logger.info(`[cron: delete out files] ${deletedReportFiles?.join(',')} (${deletedReportFiles.length}) reports are deleted`);

  const deletedSnapshotFiles = await deleteFilesInDir(snapshotsDir, 30);
  logger.info(`[cron: delete out files] ${deletedSnapshotFiles?.join(',')} (${deletedSnapshotFiles.length}) snapshots are deleted`);

  const deletedStateFiles = await deleteFilesInDir(statesDir, 30);
  logger.info(`[cron: delete out files] ${deletedStateFiles?.join(',')} (${deletedStateFiles.length}) states are deleted`);
}

const cron = new Cron('delete out files', '0 0 0 * * *', task, true);

module.exports = cron;
