#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Defaults to .git
unset GIT_DIR

ROOT_DIR=$(git rev-parse --show-toplevel)
LINT="${ROOT_DIR}/node_modules/eslint/bin/eslint.js --ext .js --no-ignore"

cd $ROOT_DIR

JSFILES=`git diff --name-only --cached --relative --diff-filter=ACM | grep '\.js$' || :`

if [ -n "$JSFILES" ]; then
  echo "$JSFILES" | xargs node $LINT
  if [ $? -ne 0 ]; then exit 1; fi
fi